export const districtsMapping: Record<string, string> = {
  臺北市: 'taipeiCity',
  臺北縣: 'taipeiCounty',
  新北市: 'newTaipeiCity',
  桃園市: 'taoyuanCity',
  桃園縣: 'taoyuanCounty',
  臺中市: 'taichungCity',
  臺中縣: 'taichungCounty',
  臺南市: 'tainanCity',
  臺南縣: 'tainanCounty',
  高雄市: 'kaohsiungCity',
  高雄縣: 'kaohsiungCounty',
  新竹縣: 'hsinchuCounty',
  新竹市: 'hsinchuCity',
  苗栗縣: 'miaoliCounty',
  彰化縣: 'changhuaCounty',
  南投縣: 'nantouCounty',
  雲林縣: 'yunlinCounty',
  嘉義縣: 'chiayiCounty',
  嘉義市: 'chiayiCity',
  屏東縣: 'pingtungCounty',
  宜蘭縣: 'yilanCounty',
  花蓮縣: 'hualienCounty',
  臺東縣: 'taitungCounty',
  澎湖縣: 'penghuCounty',
  金門縣: 'kinmenCounty',
  連江縣: 'lienchiangCounty',
  基隆市: 'keelungCity',
}
export const electionTypesMapping: Record<string, string> = {
  省長: 'governorProvince',
  省議員: 'provinceCouncilMember',
  縣市首長: 'mayor',
  縣市議員: 'councilMember',
  立法委員: 'legislator',
  區域立法委員: 'legislator-district',
  平地原住民立委: 'legislator-plainIndigenous',
  山地原住民立委: 'legislator-mountainIndigenous',
  不分區立委: 'legislator-party',
  國大代表: 'nationalAssembly',
  '總統（副總統）': 'president',
  鄉鎮市區長: 'townMayor',
  '市/區民代表': 'townCouncilMember',
  村里長: 'villageRepresentative',
}
