import { prefixOfJSONForLanding2024 } from '~/constants/environment-variables'

export type IntroItem = {
  title: string
  name: string
}
export const teamIntro2022: IntroItem[] = [
  {
    title: '監製',
    name: '簡信昌',
  },
  {
    title: '製作人',
    name: '張蘊方、李又如',
  },
  {
    title: '設計',
    name: '吳曼努',
  },
  {
    title: '工程',
    name: '陳柏維、李法賢、蘇庭葳、傅典洋、張容瑄',
  },
  {
    title: '社群',
    name: '徐湘芸',
  },
]
export const teamIntro2024: IntroItem[] = [
  {
    title: '監製',
    name: '簡信昌',
  },
  {
    title: '製作人',
    name: '劉怡馨、張蘊方、李又如',
  },
  {
    title: '設計',
    name: '吳曼努、曾立宇',
  },
  {
    title: '工程',
    name: '張容瑄、詹佳霖、陳柏維、簡信昌',
  },
  {
    title: '社群',
    name: '徐湘芸',
  },
]

export type DownloadItem = {
  title: string
  link: string
}
export const fileDownload2022: DownloadItem[] = [
  {
    title: '下載縣市長政見',
    link: 'https://whoareyou-gcs.readr.tw/politics/politics-81.csv',
  },
  {
    title: '下載縣市議員政見',
    link: 'https://whoareyou-gcs.readr.tw/politics/politics-82.csv',
  },
]
export const fileDownload2024: DownloadItem[] = [
  {
    title: '下載總統政見',
    link: `${prefixOfJSONForLanding2024}/2024president.json`,
  },
  {
    title: '下載立委政見',
    link: `${prefixOfJSONForLanding2024}/landing_legislators.json`,
  },
]

//2024首頁：總統政見-事實查核 預設資料
export const defaultFactCheckJSON = [
  {
    id: '76785',
    number: '1',
    person_id: {
      id: '226',
      name: '賴清德',
    },
    politicsCount: 2,
    politics: [],
  },
  {
    id: '76786',
    number: '2',
    person_id: {
      id: '38254',
      name: '柯文哲',
    },
    politicsCount: 0,
    politics: [],
  },
  {
    id: '76787',
    number: '3',
    person_id: {
      id: '38255',
      name: '侯友宜',
    },
    politicsCount: 0,
    politics: [],
  },
  {
    id: '76783',
    number: '4',
    person_id: {
      id: '44206',
      name: '郭台銘',
    },
    politicsCount: 0,
    politics: [],
  },
]

export const checkboxLabels = [
  {
    title: '政見提出背景',
    value: 'factCheckCount',
  },
  {
    title: '候選人過去主張',
    value: 'positionChangeCount',
  },
  {
    title: '專家看點',
    value: 'expertPointCount',
  },
  {
    title: '相似政策',
    value: 'repeatCount',
  },
]

export const defaultComparisonJSON = [
  {
    name: '賴清德',
    number: '1',
    person_id: '226',
    expertPointCount: 0,
    factCheckCount: 0,
    politicsCount: 0,
    positionChangeCount: 0,
    repeatCount: 0,
    categories_count: [],
  },
  {
    name: '柯文哲',
    number: '2',
    person_id: '38254',
    expertPointCount: 0,
    factCheckCount: 0,
    politicsCount: 0,
    positionChangeCount: 0,
    repeatCount: 0,
    categories_count: [],
  },
  {
    name: '侯友宜',
    number: '3',
    person_id: '38255',
    expertPointCount: 0,
    factCheckCount: 0,
    politicsCount: 0,
    positionChangeCount: 0,
    repeatCount: 0,
    categories_count: [],
  },
  {
    name: '郭台銘',
    number: '4',
    person_id: '44206',
    expertPointCount: 0,
    factCheckCount: 0,
    politicsCount: 0,
    positionChangeCount: 0,
    repeatCount: 0,
    categories_count: [],
  },
]

export const DefaultLegislators = {
  totalCompletionOfRegionalLegislator: 0,
  regionalLegislator: [
    {
      name: '基隆市',
      amount: 0,
      total: 6,
      areas: [
        {
          id: 28684,
          order: 1,
          name: '基隆市第01選區',
          city: '基隆市',
          candidates: [
            { id: 44417, name: '黃傑陽', year: 999, done: 0 },
            { id: 44418, name: '邱紹祐', year: 999, done: 0 },
            { id: 44419, name: '謝海菁', year: 999, done: 0 },
            { id: 40119, name: '鄭文婷', year: 1968, done: 0 },
            { id: 37401, name: '王醒之', year: 1972, done: 0 },
            { id: 40131, name: '林沛祥', year: 1977, done: 0 },
          ],
          total: 6,
          done: 0,
        },
      ],
    },
    {
      name: '高雄市',
      amount: 0,
      total: 29,
      areas: [
        {
          id: 28656,
          order: 1,
          name: '高雄市第01選區',
          city: '高雄市',
          candidates: [
            { id: 247, name: '邱議瑩', year: 1971, done: 0 },
            { id: 43117, name: '曾尹儷', year: 1963, done: 0 },
            { id: 2301, name: '林義迪', year: 1959, done: 0 },
            { id: 44379, name: '劉承智', year: 999, done: 0 },
          ],
          total: 4,
          done: 0,
        },
        {
          id: 28657,
          order: 2,
          name: '高雄市第02選區',
          city: '高雄市',
          candidates: [
            { id: 44380, name: '曹桓榮', year: 999, done: 0 },
            { id: 395, name: '邱志偉', year: 1972, done: 0 },
          ],
          total: 2,
          done: 0,
        },
        {
          id: 28658,
          order: 3,
          name: '高雄市第03選區',
          city: '高雄市',
          candidates: [
            { id: 44381, name: '郭璽', year: 999, done: 0 },
            { id: 44382, name: '陳銓霖', year: 999, done: 0 },
            { id: 28673, name: '張正達', year: 1972, done: 0 },
            { id: 38411, name: '李眉蓁', year: 1979, done: 0 },
            { id: 38413, name: '李柏毅', year: 1977, done: 0 },
          ],
          total: 5,
          done: 0,
        },
        {
          id: 28659,
          order: 4,
          name: '高雄市第04選區',
          city: '高雄市',
          candidates: [
            { id: 251, name: '林岱樺', year: 1972, done: 0 },
            { id: 33051, name: '陳若翠', year: 1969, done: 0 },
          ],
          total: 2,
          done: 0,
        },
        {
          id: 28660,
          order: 5,
          name: '高雄市第05選區',
          city: '高雄市',
          candidates: [
            { id: 44383, name: '楊椒喬', year: 999, done: 0 },
            { id: 44384, name: '張芳愉', year: 999, done: 0 },
            { id: 325, name: '李昆澤', year: 1964, done: 0 },
            { id: 36850, name: '黃柏霖', year: 1967, done: 0 },
          ],
          total: 4,
          done: 0,
        },
        {
          id: 28661,
          order: 6,
          name: '高雄市第06選區',
          city: '高雄市',
          candidates: [
            { id: 38447, name: '黃捷', year: 1993, done: 0 },
            { id: 37797, name: '郭倍宏', year: 1955, done: 0 },
            { id: 36859, name: '陳美雅', year: 1970, done: 0 },
          ],
          total: 3,
          done: 0,
        },
        {
          id: 28662,
          order: 7,
          name: '高雄市第07選區',
          city: '高雄市',
          candidates: [
            { id: 44385, name: '王和平統一', year: 999, done: 0 },
            { id: 44386, name: '朱磊', year: 999, done: 0 },
            { id: 44387, name: '洪啟修', year: 999, done: 0 },
            { id: 37081, name: '鍾易仲', year: 1982, done: 0 },
            { id: 404, name: '許智傑', year: 1966, done: 0 },
          ],
          total: 5,
          done: 0,
        },
        {
          id: 28663,
          order: 8,
          name: '高雄市第08選區',
          city: '高雄市',
          candidates: [
            { id: 44388, name: '湛秀英', year: 999, done: 0 },
            { id: 44389, name: '李明璇', year: 999, done: 0 },
            { id: 448, name: '賴瑞隆', year: 1973, done: 0 },
            { id: 38878, name: '李政憲', year: 1956, done: 0 },
          ],
          total: 4,
          done: 0,
        },
      ],
    },
    {
      name: '嘉義市',
      amount: 0,
      total: 6,
      areas: [
        {
          id: 28686,
          order: 1,
          name: '嘉義市第01選區',
          city: '嘉義市',
          candidates: [
            { id: 44423, name: '陳玥妗', year: 999, done: 0 },
            { id: 44424, name: '林智勲', year: 999, done: 0 },
            { id: 36764, name: '簡明廉', year: 1961, done: 0 },
            { id: 413, name: '王美惠', year: 1965, done: 0 },
            { id: 43386, name: '蔡松益', year: 1974, done: 0 },
            { id: 40228, name: '張秀華', year: 1957, done: 0 },
          ],
          total: 6,
          done: 0,
        },
      ],
    },
    {
      name: '金門縣',
      amount: 0,
      total: 4,
      areas: [
        {
          id: 28688,
          order: 1,
          name: '金門縣第01選區',
          city: '金門縣',
          candidates: [
            { id: 44415, name: '尚文凱', year: 999, done: 0 },
            { id: 431, name: '陳玉珍', year: 1973, done: 0 },
            { id: 36728, name: '洪和成', year: 1961, done: 0 },
            { id: 39708, name: '歐陽儀雄', year: 1973, done: 0 },
          ],
          total: 4,
          done: 0,
        },
      ],
    },
    {
      name: '屏東縣',
      amount: 0,
      total: 11,
      areas: [
        {
          id: 28679,
          order: 1,
          name: '屏東縣第01選區',
          city: '屏東縣',
          candidates: [
            { id: 44407, name: '李孟翰', year: 999, done: 0 },
            { id: 44408, name: '張庭源', year: 999, done: 0 },
            { id: 44409, name: '曾鈺庭', year: 999, done: 0 },
            { id: 9400, name: '蔣月惠', year: 1959, done: 0 },
            { id: 450, name: '鍾佳濱', year: 1965, done: 0 },
            { id: 40014, name: '鄭清原', year: 1966, done: 0 },
            { id: 40009, name: '黃明賢', year: 1983, done: 0 },
          ],
          total: 7,
          done: 0,
        },
        {
          id: 28680,
          order: 2,
          name: '屏東縣第02選區',
          city: '屏東縣',
          candidates: [
            { id: 44410, name: '蘇孟淳', year: 999, done: 0 },
            { id: 44411, name: '吳媚宮', year: 999, done: 0 },
            { id: 44412, name: '徐富癸', year: 999, done: 0 },
            { id: 36769, name: '何秋葺', year: 1970, done: 0 },
          ],
          total: 4,
          done: 0,
        },
      ],
    },
    {
      name: '宜蘭縣',
      amount: 0,
      total: 6,
      areas: [
        {
          id: 28664,
          order: 1,
          name: '宜蘭縣第01選區',
          city: '宜蘭縣',
          candidates: [
            { id: 44413, name: '邱介勲', year: 999, done: 0 },
            { id: 8294, name: '陳俊宇', year: 1975, done: 0 },
            { id: 39743, name: '黃琤婷', year: 1978, done: 0 },
            { id: 43372, name: '陳琬惠', year: 1974, done: 0 },
            { id: 39573, name: '林錦坤', year: 1964, done: 0 },
            { id: 4056, name: '林意評', year: 1989, done: 0 },
          ],
          total: 6,
          done: 0,
        },
      ],
    },
    {
      name: '桃園市',
      amount: 0,
      total: 26,
      areas: [
        {
          id: 28636,
          order: 1,
          name: '桃園市第01選區',
          city: '桃園市',
          candidates: [
            { id: 44354, name: '馬治薇', year: 999, done: 0 },
            { id: 365, name: '鄭運鵬', year: 1973, done: 0 },
            { id: 38740, name: '牛煦庭', year: 1990, done: 0 },
          ],
          total: 3,
          done: 0,
        },
        {
          id: 28637,
          order: 2,
          name: '桃園市第02選區',
          city: '桃園市',
          candidates: [
            { id: 44355, name: '王思玟', year: 999, done: 0 },
            { id: 38784, name: '涂權吉', year: 1970, done: 0 },
            { id: 36975, name: '陳志豪', year: 1978, done: 0 },
            { id: 435, name: '黃世杰', year: 1979, done: 0 },
          ],
          total: 4,
          done: 0,
        },
        {
          id: 28638,
          order: 3,
          name: '桃園市第03選區',
          city: '桃園市',
          candidates: [
            { id: 44356, name: '徐鶯慈', year: 999, done: 0 },
            { id: 43161, name: '游智彬', year: 1983, done: 0 },
            { id: 36979, name: '彭俊豪', year: 1982, done: 0 },
            { id: 445, name: '魯明哲', year: 1963, done: 0 },
            { id: 37751, name: '戴浙', year: 1948, done: 0 },
          ],
          total: 5,
          done: 0,
        },
        {
          id: 28639,
          order: 4,
          name: '桃園市第04選區',
          city: '桃園市',
          candidates: [
            { id: 44357, name: '黃明莉', year: 999, done: 0 },
            { id: 438, name: '萬美玲', year: 1969, done: 0 },
            { id: 1571, name: '范綱祥', year: 1966, done: 0 },
            { id: 40539, name: '甘乃迪', year: 1955, done: 0 },
          ],
          total: 4,
          done: 0,
        },
        {
          id: 28640,
          order: 5,
          name: '桃園市第05選區',
          city: '桃園市',
          candidates: [
            { id: 38772, name: '劉仁照', year: 1981, done: 0 },
            { id: 724, name: '賴香伶', year: 1968, done: 0 },
            { id: 393, name: '呂玉玲', year: 1961, done: 0 },
            { id: 36986, name: '易乃文', year: 1962, done: 0 },
          ],
          total: 4,
          done: 0,
        },
        {
          id: 28641,
          order: 6,
          name: '桃園市第06選區',
          city: '桃園市',
          candidates: [
            { id: 44358, name: '葉堂宇', year: 999, done: 0 },
            { id: 44359, name: '邱若華', year: 999, done: 0 },
            { id: 44360, name: '劉睿宸', year: 999, done: 0 },
            { id: 44362, name: '李慕妍', year: 999, done: 0 },
            { id: 439, name: '趙正宇', year: 1966, done: 0 },
            { id: 44361, name: '翁紹庭', year: 999, done: 0 },
          ],
          total: 6,
          done: 0,
        },
      ],
    },
    {
      name: '苗栗縣',
      amount: 0,
      total: 4,
      areas: [
        {
          id: 28667,
          order: 1,
          name: '苗栗縣第01選區',
          city: '苗栗縣',
          candidates: [
            { id: 180, name: '陳超明', year: 1951, done: 0 },
            { id: 1301, name: '康世明', year: 1969, done: 0 },
          ],
          total: 2,
          done: 0,
        },
        {
          id: 28668,
          order: 2,
          name: '苗栗縣第02選區',
          city: '苗栗縣',
          candidates: [
            { id: 39830, name: '曾玟學', year: 1987, done: 0 },
            { id: 838, name: '邱鎮軍', year: 1971, done: 0 },
          ],
          total: 2,
          done: 0,
        },
      ],
    },
    {
      name: '臺中市',
      amount: 0,
      total: 34,
      areas: [
        {
          id: 28642,
          order: 1,
          name: '臺中市第01選區',
          city: '臺中市',
          candidates: [
            { id: 44363, name: '賴信全', year: 999, done: 0 },
            { id: 44364, name: '劉燈鐘', year: 999, done: 0 },
            { id: 723, name: '蔡壁如', year: 1964, done: 0 },
            { id: 363, name: '蔡其昌', year: 1969, done: 0 },
          ],
          total: 4,
          done: 0,
        },
        {
          id: 28643,
          order: 2,
          name: '臺中市第02選區',
          city: '臺中市',
          candidates: [
            { id: 44365, name: '紀銘修', year: 999, done: 0 },
            { id: 461, name: '顏寬恒', year: 1977, done: 0 },
            { id: 683, name: '林靜儀', year: 1974, done: 0 },
            { id: 29199, name: '洪麗華', year: 1961, done: 0 },
          ],
          total: 4,
          done: 0,
        },
        {
          id: 28644,
          order: 3,
          name: '臺中市第03選區',
          city: '臺中市',
          candidates: [
            { id: 44366, name: '謝子涵', year: 999, done: 0 },
            { id: 208, name: '楊瓊瓔', year: 1964, done: 0 },
            { id: 31646, name: '張烱春', year: 1965, done: 0 },
          ],
          total: 3,
          done: 0,
        },
        {
          id: 28645,
          order: 4,
          name: '臺中市第04選區',
          city: '臺中市',
          candidates: [
            { id: 44367, name: '廖偉翔', year: 999, done: 0 },
            { id: 44368, name: '李海碩', year: 999, done: 0 },
            { id: 44369, name: '林中翊', year: 999, done: 0 },
            { id: 427, name: '張廖萬堅', year: 1965, done: 0 },
            { id: 36926, name: '陳志彬', year: 1978, done: 0 },
          ],
          total: 5,
          done: 0,
        },
        {
          id: 28646,
          order: 5,
          name: '臺中市第05選區',
          city: '臺中市',
          candidates: [
            { id: 44370, name: '謝旻汎', year: 999, done: 0 },
            { id: 44371, name: '蔡善雯', year: 999, done: 0 },
            { id: 44372, name: '林澤培', year: 999, done: 0 },
            { id: 428, name: '莊競程', year: 1980, done: 0 },
            { id: 36934, name: '苗豐隆', year: 1962, done: 0 },
            { id: 38607, name: '黃健豪', year: 1988, done: 0 },
            { id: 36933, name: '彭振芳', year: 1964, done: 0 },
            { id: 10116, name: '陳維新', year: 1966, done: 0 },
          ],
          total: 8,
          done: 0,
        },
        {
          id: 28647,
          order: 6,
          name: '臺中市第06選區',
          city: '臺中市',
          candidates: [
            { id: 44373, name: '黃千庭', year: 999, done: 0 },
            { id: 29018, name: '羅廷瑋', year: 1989, done: 0 },
            { id: 37146, name: '賀姿華', year: 1967, done: 0 },
            { id: 17147, name: '紀文清', year: 1952, done: 0 },
            { id: 38615, name: '江肇國', year: 1977, done: 0 },
          ],
          total: 5,
          done: 0,
        },
        {
          id: 28648,
          order: 7,
          name: '臺中市第07選區',
          city: '臺中市',
          candidates: [
            { id: 44374, name: '林家興', year: 999, done: 0 },
            { id: 392, name: '何欣純', year: 1973, done: 0 },
            { id: 29005, name: '林振東', year: 1960, done: 0 },
          ],
          total: 3,
          done: 0,
        },
        {
          id: 28649,
          order: 8,
          name: '臺中市第08選區',
          city: '臺中市',
          candidates: [
            { id: 390, name: '江啟臣', year: 1972, done: 0 },
            { id: 37150, name: '謝志忠', year: 1969, done: 0 },
          ],
          total: 2,
          done: 0,
        },
      ],
    },
    {
      name: '新竹市',
      amount: 0,
      total: 7,
      areas: [
        {
          id: 28685,
          order: 1,
          name: '新竹市第01選區',
          city: '新竹市',
          candidates: [
            { id: 44420, name: '柯美蘭', year: 999, done: 0 },
            { id: 44421, name: '林志潔', year: 999, done: 0 },
            { id: 44422, name: '楊清華', year: 999, done: 0 },
            { id: 444, name: '鄭正鈐', year: 1969, done: 0 },
            { id: 711, name: '邱顯智', year: 1976, done: 0 },
            { id: 37291, name: '趙福龍', year: 1955, done: 0 },
            { id: 36784, name: '王榮德', year: 1953, done: 0 },
          ],
          total: 7,
          done: 0,
        },
      ],
    },
    {
      name: '嘉義縣',
      amount: 0,
      total: 7,
      areas: [
        {
          id: 28677,
          order: 1,
          name: '嘉義縣第01選區',
          city: '嘉義縣',
          candidates: [
            { id: 441, name: '蔡易餘', year: 1981, done: 0 },
            { id: 39973, name: '詹琬蓁', year: 1977, done: 0 },
          ],
          total: 2,
          done: 0,
        },
        {
          id: 28678,
          order: 2,
          name: '嘉義縣第02選區',
          city: '嘉義縣',
          candidates: [
            { id: 44404, name: '黃一哲', year: 999, done: 0 },
            { id: 44405, name: '廖昱婧', year: 999, done: 0 },
            { id: 44406, name: '簡銘傑', year: 999, done: 0 },
            { id: 7523, name: '陳冠廷', year: 1968, done: 0 },
            { id: 333, name: '林國慶', year: 1965, done: 0 },
          ],
          total: 5,
          done: 0,
        },
      ],
    },
    {
      name: '澎湖縣',
      amount: 0,
      total: 3,
      areas: [
        {
          id: 28683,
          order: 1,
          name: '澎湖縣第01選區',
          city: '澎湖縣',
          candidates: [
            { id: 40095, name: '陳慧娟', year: 1963, done: 0 },
            { id: 1234, name: '吳政杰', year: 1967, done: 0 },
            { id: 406, name: '楊曜', year: 1966, done: 0 },
          ],
          total: 3,
          done: 0,
        },
      ],
    },
    {
      name: '彰化縣',
      amount: 0,
      total: 13,
      areas: [
        {
          id: 28669,
          order: 1,
          name: '彰化縣第01選區',
          city: '彰化縣',
          candidates: [
            { id: 44393, name: '蘇群傑', year: 999, done: 0 },
            { id: 432, name: '陳秀寳', year: 1972, done: 0 },
            { id: 885, name: '阮厚爵', year: 1970, done: 0 },
          ],
          total: 3,
          done: 0,
        },
        {
          id: 28670,
          order: 2,
          name: '彰化縣第02選區',
          city: '彰化縣',
          candidates: [
            { id: 44394, name: '楊曜聰', year: 999, done: 0 },
            { id: 436, name: '黃秀芳', year: 1971, done: 0 },
          ],
          total: 2,
          done: 0,
        },
        {
          id: 28671,
          order: 3,
          name: '彰化縣第03選區',
          city: '彰化縣',
          candidates: [
            { id: 44395, name: '洪建興', year: 999, done: 0 },
            { id: 44396, name: '吳音寧', year: 999, done: 0 },
            { id: 44397, name: '桂麗娜', year: 999, done: 0 },
            { id: 449, name: '謝衣鳯', year: 1977, done: 0 },
          ],
          total: 4,
          done: 0,
        },
        {
          id: 28672,
          order: 4,
          name: '彰化縣第04選區',
          city: '彰化縣',
          candidates: [
            { id: 44398, name: '鄭錫懋', year: 999, done: 0 },
            { id: 44399, name: '蔡念諶', year: 999, done: 0 },
            { id: 1661, name: '鄭俊雄', year: 1961, done: 0 },
            { id: 434, name: '陳素月', year: 1966, done: 0 },
          ],
          total: 4,
          done: 0,
        },
      ],
    },
    {
      name: '臺南市',
      amount: 0,
      total: 20,
      areas: [
        {
          id: 28650,
          order: 1,
          name: '臺南市第01選區',
          city: '臺南市',
          candidates: [
            { id: 44375, name: '侯陸太', year: 999, done: 0 },
            { id: 44376, name: '周宏昌', year: 999, done: 0 },
            { id: 44377, name: '林芳竹', year: 999, done: 0 },
            { id: 536, name: '魏耀乾', year: 1950, done: 0 },
            { id: 447, name: '賴惠員', year: 1961, done: 0 },
            { id: 36950, name: '蔡承攸', year: 1987, done: 0 },
          ],
          total: 6,
          done: 0,
        },
        {
          id: 28651,
          order: 2,
          name: '臺南市第02選區',
          city: '臺南市',
          candidates: [
            { id: 38652, name: '陳昆和', year: 1961, done: 0 },
            { id: 430, name: '郭國文', year: 1967, done: 0 },
            { id: 37243, name: '詹秋嫻', year: 1961, done: 0 },
          ],
          total: 3,
          done: 0,
        },
        {
          id: 28652,
          order: 3,
          name: '臺南市第03選區',
          city: '臺南市',
          candidates: [
            { id: 378, name: '陳亭妃', year: 1974, done: 0 },
            { id: 43347, name: '姚正玉', year: 1966, done: 0 },
          ],
          total: 2,
          done: 0,
        },
        {
          id: 28653,
          order: 4,
          name: '臺南市第04選區',
          city: '臺南市',
          candidates: [
            { id: 418, name: '林宜瑾', year: 1969, done: 0 },
            { id: 37790, name: '劉清田', year: 1958, done: 0 },
            { id: 239, name: '李全教', year: 1960, done: 0 },
          ],
          total: 3,
          done: 0,
        },
        {
          id: 28654,
          order: 5,
          name: '臺南市第05選區',
          city: '臺南市',
          candidates: [
            { id: 44378, name: '蕭燐洪', year: 999, done: 0 },
            { id: 419, name: '林俊憲', year: 1965, done: 0 },
            { id: 38707, name: '王家貞', year: 1957, done: 0 },
          ],
          total: 3,
          done: 0,
        },
        {
          id: 28655,
          order: 6,
          name: '臺南市第06選區',
          city: '臺南市',
          candidates: [
            { id: 412, name: '王定宇', year: 1969, done: 0 },
            { id: 717, name: '陳以信', year: 1972, done: 0 },
            { id: 29749, name: '陳永和', year: 1960, done: 0 },
          ],
          total: 3,
          done: 0,
        },
      ],
    },
    {
      name: '臺北市',
      amount: 0,
      total: 54,
      areas: [
        {
          id: 28616,
          order: 1,
          name: '臺北市第01選區',
          city: '臺北市',
          candidates: [
            { id: 44317, name: '陳執中', year: 999, done: 0 },
            { id: 44318, name: '許盛鋒', year: 999, done: 0 },
            { id: 416, name: '吳思瑤', year: 1974, done: 0 },
            { id: 38302, name: '張斯綱', year: 1971, done: 0 },
            { id: 38299, name: '侯漢廷', year: 1988, done: 0 },
            { id: 36792, name: '賴宗育', year: 1978, done: 0 },
            { id: 44319, name: '張臺勝', year: 999, done: 0 },
            { id: 15584, name: '胡金城', year: 1948, done: 0 },
          ],
          total: 8,
          done: 0,
        },
        {
          id: 28617,
          order: 2,
          name: '臺北市第02選區',
          city: '臺北市',
          candidates: [
            { id: 44320, name: '藍信祺', year: 999, done: 0 },
            { id: 38313, name: '游淑慧', year: 1976, done: 0 },
            { id: 316, name: '王世堅', year: 1960, done: 0 },
            { id: 36795, name: '郭啟源', year: 1973, done: 0 },
            { id: 36797, name: '熊嘉玲', year: 1969, done: 0 },
            { id: 44321, name: '何梅娟', year: 999, done: 0 },
          ],
          total: 6,
          done: 0,
        },
        {
          id: 28618,
          order: 3,
          name: '臺北市第03選區',
          city: '臺北市',
          candidates: [
            { id: 3912, name: '陳源發', year: 1955, done: 0 },
            { id: 41285, name: '陳一郎', year: 1943, done: 0 },
            { id: 38333, name: '王鴻薇', year: 1964, done: 0 },
            { id: 36816, name: '謝佩芬', year: 1987, done: 0 },
            { id: 38359, name: '楊時睿', year: 1988, done: 0 },
            { id: 37043, name: '高士恩', year: 1981, done: 0 },
            { id: 44322, name: '余新造', year: 999, done: 0 },
          ],
          total: 7,
          done: 0,
        },
        {
          id: 28619,
          order: 4,
          name: '臺北市第04選區',
          city: '臺北市',
          candidates: [
            { id: 44323, name: '林秋彤', year: 999, done: 0 },
            { id: 43306, name: '吳欣岱', year: 1987, done: 0 },
            { id: 425, name: '高嘉瑜', year: 1980, done: 0 },
            { id: 454, name: '李彥秀', year: 1971, done: 0 },
            { id: 37311, name: '黃啟彬', year: 1973, done: 0 },
          ],
          total: 5,
          done: 0,
        },
        {
          id: 28620,
          order: 5,
          name: '臺北市第05選區',
          city: '臺北市',
          candidates: [
            { id: 44324, name: '于美人', year: 999, done: 0 },
            { id: 44325, name: '張華特', year: 999, done: 0 },
            { id: 44326, name: '李慧曦', year: 999, done: 0 },
            { id: 44327, name: '蘇諍', year: 999, done: 0 },
            { id: 44328, name: '陳燕玉', year: 999, done: 0 },
            { id: 44329, name: '孫智麗', year: 999, done: 0 },
            { id: 38357, name: '吳沛憶', year: 1987, done: 0 },
            { id: 37506, name: '許敬民', year: 1949, done: 0 },
            { id: 38365, name: '鍾小平', year: 1962, done: 0 },
            { id: 44425, name: '林志成', year: 999, done: 0 },
          ],
          total: 10,
          done: 0,
        },
        {
          id: 28621,
          order: 6,
          name: '臺北市第06選區',
          city: '臺北市',
          candidates: [
            { id: 44330, name: '崔建章', year: 999, done: 0 },
            { id: 44331, name: '朱翊銘', year: 999, done: 0 },
            { id: 44332, name: '張雪卿', year: 999, done: 0 },
            { id: 38377, name: '羅智強', year: 1970, done: 0 },
            { id: 37078, name: '苗博雅', year: 1987, done: 0 },
          ],
          total: 5,
          done: 0,
        },
        {
          id: 28622,
          order: 7,
          name: '臺北市第07選區',
          city: '臺北市',
          candidates: [
            { id: 44333, name: '陳韋安', year: 999, done: 0 },
            { id: 38329, name: '徐巧芯', year: 1989, done: 0 },
            { id: 16920, name: '羅丹', year: 1992, done: 0 },
            { id: 36823, name: '許淑華', year: 1973, done: 0 },
            { id: 39371, name: '李承龍', year: 1958, done: 0 },
          ],
          total: 5,
          done: 0,
        },
        {
          id: 28623,
          order: 8,
          name: '臺北市第08選區',
          city: '臺北市',
          candidates: [
            { id: 44334, name: '胡之壯', year: 999, done: 0 },
            { id: 44335, name: '賴宣任', year: 999, done: 0 },
            { id: 44336, name: '張維學', year: 999, done: 0 },
            { id: 38373, name: '王閔生', year: 1975, done: 0 },
            { id: 17170, name: '夏萬浪', year: 1952, done: 0 },
            { id: 715, name: '張其祿', year: 1968, done: 0 },
            { id: 32912, name: '劉佩玲', year: 1968, done: 0 },
            { id: 224, name: '賴士葆', year: 1951, done: 0 },
          ],
          total: 8,
          done: 0,
        },
      ],
    },
    {
      name: '連江縣',
      amount: 0,
      total: 3,
      areas: [
        {
          id: 28687,
          order: 1,
          name: '連江縣第01選區',
          city: '連江縣',
          candidates: [
            { id: 44416, name: '曹爾凱', year: 999, done: 0 },
            { id: 36721, name: '李問', year: 1989, done: 0 },
            { id: 400, name: '陳雪生', year: 1952, done: 0 },
          ],
          total: 3,
          done: 0,
        },
      ],
    },
    {
      name: '新竹縣',
      amount: 0,
      total: 9,
      areas: [
        {
          id: 28665,
          order: 1,
          name: '新竹縣第01選區',
          city: '新竹縣',
          candidates: [
            { id: 44390, name: '詹紀緹', year: 999, done: 0 },
            { id: 44391, name: '劉台穠', year: 999, done: 0 },
            { id: 399, name: '徐欣瑩', year: 1972, done: 0 },
            { id: 36733, name: '余筱菁', year: 1980, done: 0 },
            { id: 10781, name: '劉復嵐', year: 1974, done: 0 },
          ],
          total: 5,
          done: 0,
        },
        {
          id: 28666,
          order: 2,
          name: '新竹縣第02選區',
          city: '新竹縣',
          candidates: [
            { id: 44392, name: '曾聖凱', year: 999, done: 0 },
            { id: 421, name: '林思銘', year: 1966, done: 0 },
            { id: 703, name: '王婉諭', year: 1979, done: 0 },
            { id: 36738, name: '黃秀龍', year: 1960, done: 0 },
          ],
          total: 4,
          done: 0,
        },
      ],
    },
    {
      name: '雲林縣',
      amount: 0,
      total: 8,
      areas: [
        {
          id: 28675,
          order: 1,
          name: '雲林縣第01選區',
          city: '雲林縣',
          candidates: [
            { id: 44402, name: '郭炳宏', year: 999, done: 0 },
            { id: 36758, name: '李昭儀', year: 1985, done: 0 },
            { id: 1004, name: '丁學忠', year: 1970, done: 0 },
            { id: 311, name: '蘇治芬', year: 1953, done: 0 },
            { id: 39945, name: '陳俊龍', year: 1969, done: 0 },
            { id: 36967, name: '吳炳輝', year: 1967, done: 0 },
          ],
          total: 6,
          done: 0,
        },
        {
          id: 28676,
          order: 2,
          name: '雲林縣第02選區',
          city: '雲林縣',
          candidates: [
            { id: 44403, name: '邱良閱', year: 999, done: 0 },
            { id: 409, name: '劉建國', year: 1969, done: 0 },
          ],
          total: 2,
          done: 0,
        },
      ],
    },
    {
      name: '新北市',
      amount: 0,
      total: 47,
      areas: [
        {
          id: 28624,
          order: 1,
          name: '新北市第01選區',
          city: '新北市',
          candidates: [
            { id: 44337, name: '翁藤原', year: 999, done: 0 },
            { id: 44338, name: '徐百弟', year: 999, done: 0 },
            { id: 44339, name: '游清池', year: 999, done: 0 },
            { id: 423, name: '洪孟楷', year: 1983, done: 0 },
            { id: 37211, name: '何博文', year: 1973, done: 0 },
          ],
          total: 5,
          done: 0,
        },
        {
          id: 28625,
          order: 2,
          name: '新北市第02選區',
          city: '新北市',
          candidates: [
            { id: 44340, name: '何淯笙', year: 999, done: 0 },
            { id: 43321, name: '李有宜', year: 1990, done: 0 },
            { id: 334, name: '林淑芬', year: 1973, done: 0 },
          ],
          total: 3,
          done: 0,
        },
        {
          id: 28626,
          order: 3,
          name: '新北市第03選區',
          city: '新北市',
          candidates: [
            { id: 38501, name: '李坤城', year: 1973, done: 0 },
            { id: 19792, name: '陳東雲', year: 1958, done: 0 },
            { id: 36879, name: '蘇卿彥', year: 1939, done: 0 },
            { id: 35101, name: '蔡明堂', year: 1958, done: 0 },
          ],
          total: 4,
          done: 0,
        },
        {
          id: 28628,
          order: 5,
          name: '新北市第05選區',
          city: '新北市',
          candidates: [
            { id: 452, name: '蘇巧慧', year: 1976, done: 0 },
            { id: 38534, name: '洪佳君', year: 1977, done: 0 },
          ],
          total: 2,
          done: 0,
        },
        {
          id: 28629,
          order: 6,
          name: '新北市第06選區',
          city: '新北市',
          candidates: [
            { id: 426, name: '張宏陸', year: 1972, done: 0 },
            { id: 40291, name: '黃淑珍', year: 1963, done: 0 },
            { id: 36892, name: '林國春', year: 1968, done: 0 },
          ],
          total: 3,
          done: 0,
        },
        {
          id: 28630,
          order: 7,
          name: '新北市第07選區',
          city: '新北市',
          candidates: [
            { id: 44344, name: '劉書婷', year: 999, done: 0 },
            { id: 451, name: '羅致政', year: 1964, done: 0 },
            { id: 38507, name: '葉元之', year: 1974, done: 0 },
          ],
          total: 3,
          done: 0,
        },
        {
          id: 28631,
          order: 8,
          name: '新北市第08選區',
          city: '新北市',
          candidates: [
            { id: 44345, name: '張智倫', year: 999, done: 0 },
            { id: 710, name: '邱臣遠', year: 1981, done: 0 },
            { id: 38328, name: '吳崢', year: 1989, done: 0 },
          ],
          total: 3,
          done: 0,
        },
        {
          id: 28633,
          order: 10,
          name: '新北市第10選區',
          city: '新北市',
          candidates: [
            { id: 44346, name: '袁興', year: 999, done: 0 },
            { id: 417, name: '吳琪銘', year: 1963, done: 0 },
            { id: 36907, name: '林金結', year: 1968, done: 0 },
            { id: 36818, name: '孟藹倫', year: 1955, done: 0 },
          ],
          total: 4,
          done: 0,
        },
        {
          id: 28634,
          order: 11,
          name: '新北市第11選區',
          city: '新北市',
          candidates: [
            { id: 44347, name: '陳聖', year: 999, done: 0 },
            { id: 44348, name: '鄭添泉', year: 999, done: 0 },
            { id: 44350, name: '魏趨安', year: 999, done: 0 },
            { id: 37132, name: '曾柏瑜', year: 1991, done: 0 },
            { id: 230, name: '羅明才', year: 1967, done: 0 },
            { id: 44349, name: '張家榛', year: 999, done: 0 },
          ],
          total: 6,
          done: 0,
        },
        {
          id: 28635,
          order: 12,
          name: '新北市第12選區',
          city: '新北市',
          candidates: [
            { id: 44351, name: '李佳蒨', year: 999, done: 0 },
            { id: 44352, name: '陳長志', year: 999, done: 0 },
            { id: 44353, name: '楊木火', year: 999, done: 0 },
            { id: 446, name: '賴品妤', year: 1992, done: 0 },
            { id: 38548, name: '黃瑞傳', year: 1950, done: 0 },
            { id: 38552, name: '廖先翔', year: 1988, done: 0 },
          ],
          total: 6,
          done: 0,
        },
        {
          id: 28632,
          order: 9,
          name: '新北市第09選區',
          city: '新北市',
          candidates: [
            { id: 255, name: '林德福', year: 1953, done: 0 },
            { id: 20152, name: '莊銘淵', year: 1973, done: 0 },
            { id: 36902, name: '陳愷寧', year: 1995, done: 0 },
          ],
          total: 3,
          done: 0,
        },
        {
          id: 28627,
          order: 4,
          name: '新北市第04選區',
          city: '新北市',
          candidates: [
            { id: 44341, name: '蔣欣璋', year: 999, done: 0 },
            { id: 44342, name: '蘇輝湟', year: 999, done: 0 },
            { id: 44343, name: '洪懿馥', year: 999, done: 0 },
            { id: 322, name: '吳秉叡', year: 1966, done: 0 },
            { id: 28612, name: '邱吉均', year: 1958, done: 0 },
          ],
          total: 5,
          done: 0,
        },
      ],
    },
    {
      name: '花蓮縣',
      amount: 0,
      total: 4,
      areas: [
        {
          id: 28682,
          order: 1,
          name: '花蓮縣第01選區',
          city: '花蓮縣',
          candidates: [
            { id: 6829, name: '許願神', year: 1954, done: 0 },
            { id: 285, name: '傅崐萁', year: 1962, done: 0 },
            { id: 6931, name: '周玉梅', year: 1969, done: 0 },
            { id: 40074, name: '張美慧', year: 1970, done: 0 },
          ],
          total: 4,
          done: 0,
        },
      ],
    },
    {
      name: '南投縣',
      amount: 0,
      total: 8,
      areas: [
        {
          id: 28673,
          order: 1,
          name: '南投縣第01選區',
          city: '南投縣',
          candidates: [
            { id: 44400, name: '許文忠', year: 999, done: 0 },
            { id: 44401, name: '李圓恩', year: 999, done: 0 },
            { id: 7551, name: '蔡銘軒', year: 1984, done: 0 },
            { id: 5362, name: '林金潭', year: 1957, done: 0 },
            { id: 402, name: '馬文君', year: 1965, done: 0 },
          ],
          total: 5,
          done: 0,
        },
        {
          id: 28674,
          order: 2,
          name: '南投縣第02選區',
          city: '南投縣',
          candidates: [
            { id: 39919, name: '游顥', year: 1983, done: 0 },
            { id: 990, name: '陳癸佑', year: 1968, done: 0 },
            { id: 698, name: '蔡培慧', year: 1971, done: 0 },
          ],
          total: 3,
          done: 0,
        },
      ],
    },
    {
      name: '臺東縣',
      amount: 0,
      total: 6,
      areas: [
        {
          id: 28681,
          order: 1,
          name: '臺東縣第01選區',
          city: '臺東縣',
          candidates: [
            { id: 44414, name: '黃婉茹', year: 999, done: 0 },
            { id: 651, name: '賴坤成', year: 1964, done: 0 },
            { id: 2380, name: '許瑞貴', year: 1955, done: 0 },
            { id: 410, name: '劉櫂豪', year: 1967, done: 0 },
            { id: 43390, name: '陳長宏', year: 1965, done: 0 },
            { id: 1184, name: '黃建賓', year: 1978, done: 0 },
          ],
          total: 6,
          done: 0,
        },
      ],
    },
  ],
  totalCompletionOfAboriginalRegionalLegislator: 0,
  aboriginalLegislator: [
    {
      name: '全國',
      amount: 0,
      total: 9,
      areas: [
        {
          id: 28614,
          order: 0,
          name: '全國',
          city: '全國',
          candidates: [
            { id: 36990, name: '高畹芯', year: 1959, done: 0 },
            {
              id: 43997,
              name: '伍麗華 Saidhai．Tahovecahe',
              year: 1969,
              done: 0,
            },
            { id: 1697, name: '張子孝', year: 1960, done: 0 },
            { id: 1190, name: '胡黃廣文', year: 1969, done: 0 },
            { id: 44426, name: '林果', year: 999, done: 0 },
            { id: 314, name: '孔文吉', year: 1957, done: 0 },
            { id: 37184, name: '林世偉', year: 1967, done: 0 },
            { id: 44427, name: '盧縣一', year: 999, done: 0 },
            {
              id: 44428,
              name: '李我要單列族名我的布農族名字是 Savungaz Valincinan',
              year: 999,
              done: 0,
            },
          ],
          total: 9,
          done: 0,
        },
      ],
    },
  ],
  totalCompletionOfFlatAboriginalRegionalLegislator: 0,
  flatAboriginalLegislator: [
    {
      name: '全國',
      amount: 0,
      total: 10,
      areas: [
        {
          id: 28615,
          order: 0,
          name: '全國',
          city: '全國',
          candidates: [
            { id: 8211, name: '陳政宗', year: 1973, done: 0 },
            { id: 44429, name: '洪曹純明', year: 999, done: 0 },
            { id: 343, name: '陳瑩', year: 1972, done: 0 },
            { id: 36987, name: '黃仁', year: 1962, done: 0 },
            { id: 43056, name: '忠仁・達祿斯', year: 1961, done: 0 },
            { id: 40282, name: '高美珠', year: 1970, done: 0 },
            { id: 44430, name: '吳建智咖啡哥', year: 999, done: 0 },
            { id: 44431, name: '陳國榮', year: 999, done: 0 },
            { id: 44003, name: '鄭天財 Sra．Kacaw', year: 1956, done: 0 },
            { id: 44432, name: '米甘幹・理佛克', year: 999, done: 0 },
          ],
          total: 10,
          done: 0,
        },
      ],
    },
  ],
  totalCompletionOfNonRegionalLegislator: 0,
  nonRegionalLegislator: [
    {
      name: '全國',
      amount: 0,
      total: 16,
      areas: [
        {
          id: 28613,
          order: 0,
          name: '全國',
          city: '全國',
          candidates: [
            { id: 25, name: '民主進步黨', done: 0 },
            { id: 28, name: '台灣團結聯盟', done: 0 },
            { id: 31, name: '中華統一促進黨', done: 0 },
            { id: 32, name: '親民黨', done: 0 },
            { id: 35, name: '新黨', done: 0 },
            { id: 37, name: '時代力量', done: 0 },
            { id: 22, name: '中國國民黨', done: 0 },
            { id: 62, name: '台灣基進', done: 0 },
            { id: 64, name: '台灣維新', done: 0 },
            { id: 103, name: '人民最大黨', done: 0 },
            { id: 149, name: '小民參政歐巴桑聯盟', done: 0 },
            { id: 39, name: '台灣綠黨', done: 0 },
            { id: 164, name: '臺灣雙語無法黨', done: 0 },
            { id: 165, name: '台灣麻將最大黨', done: 0 },
            { id: 166, name: '司法改革黨', done: 0 },
            { id: 102, name: '制度救世島', done: 0 },
          ],
          total: 16,
          done: 0,
        },
      ],
    },
  ],
}
