steps:
  # build docker image for target sub-pacakge
  - name: gcr.io/cloud-builders/docker
    id: Build Image
    env:
    - 'NEXT_PUBLIC_ENV=$_ENV'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp yarn.lock Dockerfile .dockerignore packages/$_TARGET_PACKAGE
        cd packages/$_TARGET_PACKAGE
        printenv > .env.local
        docker build -t gcr.io/$PROJECT_ID/$_IMAGE_NAME:${BRANCH_NAME}_${SHORT_SHA} .

  # build docker image for target sub-pacakge
  - name: gcr.io/cloud-builders/docker
    id: Push Image
    args:
      - push
      - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:${BRANCH_NAME}_${SHORT_SHA}'

  # Deploy container image to Cloud Runs
  - name: gcr.io/cloud-builders/gcloud
    id: Deploy Image
    entrypoint: 'bash'
    args:
      - '-c'
      - |

        # read cloud run service names from substitution variable
        IFS=',' read -r -a cloud_runs <<< "$_CLOUD_RUN_SERVICE_NAMES"

        for cr in "${cloud_runs[@]}"
        do

        # deploy cloud run service iteratively
        gcloud run deploy "$cr" --image gcr.io/$PROJECT_ID/$_IMAGE_NAME:${BRANCH_NAME}_${SHORT_SHA} --region asia-east1

        done

timeout: 1200s

images: ['gcr.io/$PROJECT_ID/$_IMAGE_NAME:${BRANCH_NAME}_${SHORT_SHA}']

substitutions:
  _TARGET_PACKAGE: '' # default value
  _IMAGE_NAME: '' # default value
  _CLOUD_RUN_SERVICE_NAMES: '' # default value
  _ENV: 'dev' # default value
