export const getToastMessages = (t: (key: string) => string) => {
  return {
    followCategoryFailed: t('follow-category-failed'),
    unfollowCategoryFailed: t('unfollow-category-failed'),
    moreActionError: t('more-action-error'),
    addCommentFailed: t('add-comment-failed'),
    editCommentFailed: t('edit-comment-failed'),
    likeCommentFailed: t('like-comment-failed'),
    unlikeCommentFailed: t('unlike-comment-failed'),
    deleteCommentFailed: t('delete-comment-failed'),
    followMemberFailed: t('follow-member-failed'),
    unfollowMemberFailed: t('unfollow-member-failed'),
    pickStoryFailed: t('pick-story-failed'),
    deletePickFailed: t('delete-pick-failed'),
    addBookmarkFailed: t('add-bookmark-failed'),
    deleteBookmarkFailed: t('delete-bookmark-failed'),
    copyStoryLinkSuccess: t('copy-story-link-success'),
    copyInvitationCode: t('copy-invitation-code'),
    unlockStorySuccess: t('unlock-story-success'),
    payFailedInsufficient: t('pay-failed-insufficient'),
    payFailedUnowknown: t('pay-failed-unknown'),
    blockMemberSuccess: t('block-member-success'),
    unblockMemberSuccess: t('unblock-member-success'),
    blockMemberFailed: t('block-member-failed'),
    unblockMemberFailed: t('unblock-member-failed'),
    addStoryToCollectionSuccess: t('add-story-to-collection-success'),
    addStoryToCollectionFailed: t('add-story-to-collection-failed'),
    createCollectionFailed: t('create-collection-failed'),
    deleteCollectionSuccess: t('delete-collection-success'),
    deleteCollectionFailed: t('delete-collection-failed'),
    updateProfileFailed: t('update-profile-failed'),
    addBookmarkSuccess: t('add-bookmark-success'),
    removeBookmarkSuccess: t('remove-bookmark-success'),
  } as const
}

// 保留原始常數供非 React 環境使用
const TOAST_MESSAGE = {
  followCategoryFailed: '新增類別失敗，請重新嘗試',
  unfollowCategoryFailed: '刪除類別失敗，請重新嘗試',
  moreActionError: '有點怪怪的，請稍後再試',
  addCommentFailed: '發布留言失敗，請重新嘗試',
  editCommentFailed: '編輯留言失敗，請重新嘗試',
  likeCommentFailed: '按讚留言失敗，請重新嘗試',
  unlikeCommentFailed: '取消按讚留言失敗，請重新嘗試',
  deleteCommentFailed: '刪除留言失敗，請重新嘗試',
  followMemberFailed: '追蹤失敗，請重新嘗試',
  unfollowMemberFailed: '取消追蹤失敗，請重新嘗試',
  pickStoryFailed: '加入精選失敗，請重新嘗試',
  deletePickFailed: '移除精選失敗，請重新嘗試',
  addBookmarkFailed: '加入書籤失敗，請重新嘗試',
  deleteBookmarkFailed: '刪除書籤失敗，請重新嘗試',
  copyStoryLinkSuccess: '已複製連結',
  copyInvitationCode: '已複製邀請碼',
  unlockStorySuccess: '已成功解鎖',
  payFailedInsufficient: '讀選點數餘額不足',
  payFailedUnowknown: '支付失敗，請重新嘗試',
  // TODO: to be added
  blockMemberSuccess: '已封鎖',
  unblockMemberSuccess: '已取消封鎖',
  blockMemberFailed: '封鎖失敗，請重新嘗試',
  unblockMemberFailed: '取消封鎖失敗，請重新嘗試',
  addStoryToCollectionSuccess: '成功加入集錦',
  addStoryToCollectionFailed: '加入集錦失敗，請重新嘗試',
  createCollectionFailed: '建立集錦失敗，請重新嘗試',
  deleteCollectionSuccess: '成功刪除集錦',
  deleteCollectionFailed: '刪除集錦失敗，請重新嘗試',
  updateProfileFailed: '編輯個人檔案失敗，請重新嘗試',
  addBookmarkSuccess: '已加入書籤',
  removeBookmarkSuccess: '已移除書籤',
} as const

export default TOAST_MESSAGE
